patches:
  - selectors:
      - $
    values:
      consumers:
        - keyauth_credentials:
            - id: 3b264e21-8e9b-4080-b745-625218446563
              key: demo-api-key-2024
          username: demo
          tags:
            - managed-by-deck
            - generated-from-oas
