add-plugins:
  - selectors:
      - $.services[*].routes[?(@.name=='item-api_createitem')]
    plugins:
      - config:
          anonymous: null
          hide_credentials: false
          identity_realms:
            - id: null
              region: null
              scope: cp
          key_in_body: false
          key_in_header: true
          key_in_query: true
          key_names:
            - apikey
          realm: null
          run_on_preflight: true
        enabled: true
        name: key-auth
        protocols:
          - grpc
          - grpcs
          - http
          - https
          - ws
          - wss
  - selectors:
      - $.services[*].routes[?(@.name=='item-api_getitems')]
    plugins:
      - config:
          compound_identifier: null
          consumer_groups: null
          dictionary_name: kong_rate_limiting_counters
          disable_penalty: false
          enforce_consumer_groups: false
          error_code: 429
          error_message: API rate limit exceeded
          header_name: null
          hide_client_headers: false
          identifier: consumer
          limit:
            - 5
          lock_dictionary_name: kong_locks
          namespace: tePDGfhlwZBWgmoAUgIAi0pxxnAC0QYU
          path: null
          redis:
            cluster_addresses: null
            cluster_max_redirections: 5
            cluster_nodes: null
            connect_timeout: 2000
            connection_is_proxied: false
            database: 0
            host: 127.0.0.1
            keepalive_backlog: null
            keepalive_pool_size: 256
            password: null
            port: 6379
            read_timeout: 2000
            redis_proxy_type: null
            send_timeout: 2000
            sentinel_addresses: null
            sentinel_master: null
            sentinel_nodes: null
            sentinel_password: null
            sentinel_role: null
            sentinel_username: null
            server_name: null
            ssl: false
            ssl_verify: false
            timeout: 2000
            username: null
          retry_after_jitter_max: 0
          strategy: local
          sync_rate: null
          window_size:
            - 10
          window_type: sliding
        enabled: true
        name: rate-limiting-advanced
        protocols:
          - grpc
          - grpcs
          - http
          - https
