_format_version: "3.0"
_konnect:
  control_plane_name: serverless-default
consumers:
- keyauth_credentials:
  - id: 3b264e21-8e9b-4080-b745-625218446563
    key: demo-api-key-2024
  tags:
  - managed-by-deck
  - generated-from-oas
  username: demo
services:
- host: host.docker.internal
  id: 21d1422f-4508-5448-a67b-f542659b4e87
  name: item-api
  plugins: []
  port: 3000
  protocol: http
  routes:
  - id: f96fd075-618b-5fd2-bf30-02154e7a823c
    methods:
    - GET
    name: item-api_getitems
    paths:
    - /items
    plugins:
    - config:
        compound_identifier: null
        consumer_groups: null
        dictionary_name: kong_rate_limiting_counters
        disable_penalty: false
        enforce_consumer_groups: false
        error_code: 429
        error_message: API rate limit exceeded
        header_name: null
        hide_client_headers: false
        identifier: consumer
        limit:
        - 10
        lock_dictionary_name: kong_locks
        namespace: tePDGfhlwZBWgmoAUgIAi0pxxnAC0QYU
        path: null
        redis:
          cluster_addresses: null
          cluster_max_redirections: 5
          cluster_nodes: null
          connect_timeout: 2000
          connection_is_proxied: false
          database: 0
          host: 127.0.0.1
          keepalive_backlog: null
          keepalive_pool_size: 256
          password: null
          port: 6379
          read_timeout: 2000
          redis_proxy_type: null
          send_timeout: 2000
          sentinel_addresses: null
          sentinel_master: null
          sentinel_nodes: null
          sentinel_password: null
          sentinel_role: null
          sentinel_username: null
          server_name: null
          ssl: false
          ssl_verify: false
          timeout: 2000
          username: null
        retry_after_jitter_max: 0
        strategy: local
        sync_rate: null
        window_size:
        - 10
        window_type: sliding
      enabled: true
      name: rate-limiting-advanced
      protocols:
      - grpc
      - grpcs
      - http
      - https
    regex_priority: 200
    strip_path: false
    tags:
    - managed-by-deck
    - generated-from-oas
  - id: ff193da2-c102-512a-8002-ddef1049816c
    methods:
    - POST
    name: item-api_createitem
    paths:
    - /items
    plugins:
    - config:
        anonymous: null
        hide_credentials: false
        identity_realms:
        - id: null
          region: null
          scope: cp
        key_in_body: false
        key_in_header: true
        key_in_query: true
        key_names:
        - apikey
        realm: null
        run_on_preflight: true
      enabled: true
      name: key-auth
      protocols:
      - grpc
      - grpcs
      - http
      - https
      - ws
      - wss
    regex_priority: 200
    strip_path: false
    tags:
    - managed-by-deck
    - generated-from-oas
  - id: c68b3a1a-b0f8-57e9-b810-52448b9ab6ab
    methods:
    - DELETE
    name: item-api_deleteitem
    paths:
    - ~/items/(?<id>[^#?/]+)$
    plugins: []
    regex_priority: 100
    strip_path: false
    tags:
    - managed-by-deck
    - generated-from-oas
  - id: 099b5c87-52e8-51f7-bb6d-ecbb8e062842
    methods:
    - GET
    name: item-api_getitembyid
    paths:
    - ~/items/(?<id>[^#?/]+)$
    plugins: []
    regex_priority: 100
    strip_path: false
    tags:
    - managed-by-deck
    - generated-from-oas
  - id: 020e4bf6-50d3-5537-b4db-7ba755cc5cc1
    methods:
    - PATCH
    name: item-api_patchitem
    paths:
    - ~/items/(?<id>[^#?/]+)$
    plugins: []
    regex_priority: 100
    strip_path: false
    tags:
    - managed-by-deck
    - generated-from-oas
  - id: 0acd5bf7-7351-576b-a275-d892cbda71b8
    methods:
    - PUT
    name: item-api_updateitem
    paths:
    - ~/items/(?<id>[^#?/]+)$
    plugins: []
    regex_priority: 100
    strip_path: false
    tags:
    - managed-by-deck
    - generated-from-oas
  tags:
  - managed-by-deck
  - generated-from-oas
  - team:backend
upstreams: []
