on: push
jobs:
  deploy_items-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: "18"

      - name: Install DecK
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.47.0/deck_1.47.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp
          cp /tmp/deck /usr/local/bin/

      - name: Install Insomnia
        run: |
          curl -sL https://github.com/Kong/insomnia/releases/download/core%4011.1.0-beta.3/inso-linux-x64-11.1.0-beta.3.tar.xz -o inso.tar.xz
          sudo tar -xf inso.tar.xz -C /tmp/
          cp /tmp/inso /usr/local/bin/

      - name: Backup Existing Configuration
        run: deck gateway dump --konnect-token kpat_QjviY1aJEiJTR5Wg6egnKJOsFpD5jlXq10L4BzowGHWwlEjvR --konnect-control-plane-name "serverless-default" --tls-skip-verify > config/kong-backup.yaml

      - name: Lint OpenAPI Spec
        run: inso lint spec config/items-oas.yaml --ci

      - name: Generate Kong Configuration
        run: deck file openapi2kong --spec config/items-oas.yaml --output-file config/items-deck.yaml

      - name: Patch Kong Configuration With Target Control Plane
        run: deck file patch -s config/items-deck.yaml config/patch.yaml -o config/items-deck.yaml

      - name: Add Kong Plugins and Consumers
        run: |
          # Add plugins from file
          deck file add-plugins -s config/items-deck.yaml config/add-plugins.yaml -o config/items-deck.yaml
          # Add consumers
          deck file patch -s config/items-deck.yaml config/add-consumers.yaml -o config/items-deck.yaml

      - name: Apply New Configuration
        run: |
          deck gateway sync --konnect-token kpat_QjviY1aJEiJTR5Wg6egnKJOsFpD5jlXq10L4BzowGHWwlEjvR --konnect-control-plane-name "serverless-default" --tls-skip-verify config/items-deck.yaml

      - name: Back out Changes on Failure
        if: failure()
        run: |
          echo "Something went wrong. Rolling back changes."
          deck gateway sync --konnect-token kpat_QjviY1aJEiJTR5Wg6egnKJOsFpD5jlXq10L4BzowGHWwlEjvR --konnect-control-plane-name "serverless-default" --tls-skip-verify config/kong-backup.yaml